spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udee
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level.org.springframework.web: DEBUG


